from __future__ import annotations

import logging

from sub_checker.agents.base import ADD_FINDING_TOOL, BaseCheckerAgent
from sub_checker.config import Config
from sub_checker.models import Manuscript
from sub_checker.services.citation_verifier import (
    format_verification_report,
    verify_references,
)
from sub_checker.services.crossref import CrossrefClient
from sub_checker.services.pubmed import PubMedClient
from sub_checker.services.semantic_scholar import SemanticScholarClient
from sub_checker.tools.manuscript_tools import (
    TOOL_GET_REFERENCE_LIST,
    TOOL_READ_SECTION,
    get_reference_list,
    read_section,
)
from sub_checker.tools.pubmed_tools import (
    TOOL_GET_ABSTRACT,
    TOOL_SEARCH_LITERATURE,
    get_abstract,
    search_literature,
)

logger = logging.getLogger("sub_checker.agents.citation_claim")


class CitationClaimAgent(BaseCheckerAgent):
    name = "citation_claim"

    def __init__(self, model: str = "claude-opus-4-8"):
        super().__init__(model=model)
        self._manuscript: Manuscript | None = None
        self._pubmed: PubMedClient | None = None
        self._s2: SemanticScholarClient | None = None
        self._verification_report: str = ""

    def _default_system_prompt(self) -> str:
        return (
            "You are a citation verification expert. Your job is to verify that EVERY "
            "citation in the manuscript is supported by the actual referenced paper.\n\n"
            "## Pre-Verification Report\n\n"
            "A MULTI-SOURCE VERIFICATION REPORT is provided in your initial message.\n"
            "This report was generated by querying PubMed, Semantic Scholar, AND Crossref\n"
            "in parallel, then cross-validating results. Each reference has a confidence\n"
            "score and verification status.\n\n"
            "TRUST this report for reference existence. Focus your effort on:\n"
            "- Verifying that claims in the text are actually supported by the cited papers\n"
            "- For 'verified' references: use get_abstract to compare claim vs abstract\n"
            "- For 'not_found' references: note this in your finding (may be very recent)\n\n"
            "## Workflow\n\n"
            "1. Review the pre-verification report for reference existence/validity\n"
            "2. Read the reference list and each manuscript section\n"
            "3. For EACH citation:\n"
            "   a. Identify the CLAIM being made\n"
            "   b. Check the pre-verification status\n"
            "   c. For verified/likely_valid refs: use get_abstract to check claim support\n"
            "   d. Report your verdict via add_finding\n\n"
            "## Verdict Categories\n\n"
            "- **SUPPORTS** (severity=info): Abstract clearly supports the claim\n"
            "- **PARTIALLY_SUPPORTS** (severity=info): Related but doesn't fully address\n"
            "- **CONTRADICTS** (severity=error): Abstract contradicts the claim\n"
            "- **INSUFFICIENT** (severity=warning): Not enough info to verify\n"
            "- **NOT_FOUND** (severity=warning): Paper not found (check pre-verification)\n"
            "- **NO_ABSTRACT** (severity=warning): Paper found but no abstract available\n\n"
            "## Important Rules\n\n"
            "- Verify EVERY citation systematically\n"
            "- search_literature searches PubMed first, then Semantic Scholar as fallback\n"
            "- Include citation number, claim text, and verdict in each finding\n"
            "- For self-citations or unpublished: report as info\n"
        )

    def _build_initial_message(self, manuscript: Manuscript, config: Config) -> str:
        """Override to inject multi-source verification report."""
        base_msg = super()._build_initial_message(manuscript, config)
        if self._verification_report:
            return base_msg + "\n\n" + self._verification_report
        return base_msg

    def get_tools(self) -> list[dict]:
        return [
            TOOL_READ_SECTION,
            TOOL_GET_REFERENCE_LIST,
            TOOL_SEARCH_LITERATURE,
            TOOL_GET_ABSTRACT,
            ADD_FINDING_TOOL,
        ]

    async def handle_tool_call(self, tool_name: str, tool_input: dict) -> str:
        ms = self._manuscript
        assert ms is not None
        if tool_name == "read_section":
            return read_section(ms, tool_input["section_name"])
        if tool_name == "get_reference_list":
            return get_reference_list(ms)
        if tool_name == "search_literature":
            assert self._pubmed is not None
            assert self._s2 is not None
            return await search_literature(
                self._pubmed,
                self._s2,
                tool_input["author"],
                tool_input["year"],
                tool_input.get("title_keywords", ""),
            )
        if tool_name == "get_abstract":
            assert self._pubmed is not None
            assert self._s2 is not None
            return await get_abstract(self._pubmed, self._s2, tool_input["paper_id"])
        return f"Unknown tool: {tool_name}"

    async def run(self, manuscript: Manuscript, config: Config):
        self._manuscript = manuscript
        self._pubmed = PubMedClient(
            email=config.claim.pubmed_email,
            api_key=config.claim.pubmed_api_key,
            max_concurrent=config.claim.max_concurrent_pubmed,
        )
        self._s2 = SemanticScholarClient(max_concurrent=3)
        crossref = CrossrefClient(max_concurrent=3, mailto=config.claim.pubmed_email)

        try:
            # Run multi-source verification as harness pre-pass
            if manuscript.reference_section:
                ref_lines = [
                    line
                    for line in manuscript.reference_section.strip().split("\n")
                    if line.strip()
                ]
                logger.info(
                    "Running multi-source verification for %d references...", len(ref_lines)
                )
                verified = await verify_references(ref_lines, self._pubmed, self._s2, crossref)
                self._verification_report = format_verification_report(verified)
                logger.info("Verification complete: %s", self._verification_report[:200])

            return await super().run(manuscript, config)
        finally:
            await self._pubmed.close()
            await self._s2.close()
            await crossref.close()
