"""Simple i18n for report output. Supports en and zh-TW."""

from __future__ import annotations

from typing import Any

LOCALES: dict[str, dict[str, str]] = {
    "en": {
        # Report header
        "report_title": "Sub-Checker Report",
        "journal_label": "Journal",
        "journal_not_specified": "Not specified",
        "generated": "Generated",
        "est_cost": "Est. Cost",
        # Summary
        "summary": "Summary",
        "errors": "Errors",
        "warnings": "Warnings",
        "info": "Info",
        "total": "Total",
        # Table headers
        "severity": "Severity",
        "location": "Location",
        "message": "Message",
        "suggestion": "Suggestion",
        # Severity labels
        "error": "ERROR",
        "warning": "WARNING",
        "info_label": "INFO",
        # Misc
        "no_issues": "No issues found.",
        "generated_by": "Generated by",
        # Checker names
        "checker_typo_grammar": "Typo & Grammar",
        "checker_figure_table": "Figure & Table",
        "checker_citation_exist": "Citation Existence",
        "checker_citation_format": "Citation Format",
        "checker_journal_guidelines": "Journal Guidelines",
        "checker_logic": "Logic Consistency",
        "checker_citation_claim": "Citation-Claim Verification",
    },
    "zh-TW": {
        # Report header
        "report_title": "投稿前文稿檢查報告",
        "journal_label": "目標期刊",
        "journal_not_specified": "未指定",
        "generated": "產生時間",
        "est_cost": "預估費用",
        # Summary
        "summary": "摘要",
        "errors": "錯誤",
        "warnings": "警告",
        "info": "資訊",
        "total": "合計",
        # Table headers
        "severity": "嚴重程度",
        "location": "位置",
        "message": "問題描述",
        "suggestion": "建議",
        # Severity labels
        "error": "錯誤",
        "warning": "警告",
        "info_label": "資訊",
        # Misc
        "no_issues": "未發現問題。",
        "generated_by": "由以下工具產生",
        # Checker names
        "checker_typo_grammar": "拼字與文法",
        "checker_figure_table": "圖表檢查",
        "checker_citation_exist": "引用完整性",
        "checker_citation_format": "引用格式",
        "checker_journal_guidelines": "期刊投稿規範",
        "checker_logic": "邏輯一致性",
        "checker_citation_claim": "引用-主張驗證",
    },
}

DEFAULT_LANG = "en"


def t(key: str, lang: str = DEFAULT_LANG, **kwargs: Any) -> str:
    """Translate a key. Falls back to English if key not found."""
    locale = LOCALES.get(lang, LOCALES["en"])
    text = locale.get(key, LOCALES["en"].get(key, key))
    if kwargs:
        text = text.format(**kwargs)
    return text


def checker_display_name(checker_name: str, lang: str = DEFAULT_LANG) -> str:
    """Get localized display name for a checker.

    t() returns the key itself when missing (never falsy), so an unknown
    checker must be detected explicitly to fall back to the raw name.
    """
    key = f"checker_{checker_name}"
    label = t(key, lang)
    return checker_name if label == key else label
